name: Auto Create Pull Request
on:
  push:
    branches:
      - main 

# This gives the automated script permission to make changes and open PRs
permissions:
  contents: write
  pull-requests: write

jobs:
  make-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # This creates a dummy change inside the runner to ensure there is something new to put in a PR
      - name: Simulate Sandbox Change
        run: |
          date +%s > sandbox-deploy-timestamp.txt

      - name: Open Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Updated Apex classes from Sandbox'
          title: 'Review Apex Changes from Sandbox'
          body: 'This PR was automatically created because new Apex code was deployed and pushed.'
          branch: review-sandbox-changes
          base: main
